version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: postgres 
      
      # Variaveis para o script init
      N8N_DB_USER: ${N8N_DB_USER}
      N8N_DB_PASSWORD: ${N8N_DB_PASSWORD}
      N8N_DB_NAME: ${N8N_DB_NAME}
      
      API_DB_USER: ${API_DB_USER}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      API_DB_NAME: ${API_DB_NAME}
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
      - ./infra/postgres/init-dbs.sql:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ROOT_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal-net

  n8n-main:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      N8N_HOST: ${N8N_HOST}
      N8N_PROTOCOL: ${N8N_PROTOCOL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_PROXY_HOPS: 1
      
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${N8N_DB_NAME}
      DB_POSTGRESDB_USER: ${N8N_DB_USER}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}
      
      NODE_OPTIONS: "--max-old-space-size=4096"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: "168"
      N8N_SECURE_COOKIE: false
    volumes:
      - ./volumes/n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal-net

  api:
    image: genildodocker/api-gb-core
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${API_DB_USER}:${API_DB_PASSWORD}@postgres:5432/${API_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal-net

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - internal-net
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
          max-file: "3"

networks:
  internal-net: